[package]
name = "lanred-dev/fluid"
description = "Alternative to Roblox's TweenService"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
authors = ["Lanred"]
realm = "shared"
license = "MIT"
include = ["default.project.json", "src", "src/**", "LICENSE", "wally.toml"]
exclude = ["**"]

[dependencies]
